contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tutorial channel"
    url: https://nfcore.slack.com/channels/tutorial
    about: Discussion about the nf-core/tutorial pipeline
